


- hosts: all
  become: yes

  tasks:
    - name: Add SSH key for root
      ansible.builtin.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/ansible_id.pub') }}"
